version: '3.3'

networks:
  docker_mainflux-base-net:
    external: true

services:

  users:
    build:
      context: ./users
      dockerfile: Dockerfile-dev
    volumes:
      - './users:/usr/src/app'
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - MAINFLUX_BROKER_URL=https://172.18.0.4/ # when running locally connect to nginx server on mainflux
    external_links:
      - docker_mainflux-base-net
    networks:
      - default
      - docker_mainflux-base-net # make sure that you are connected to the mainflux network if running on the same host
    depends_on:  # new
      - users-db


  users-db:
    build:
      context: ./users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    networks:
      - default # use its own docker network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    networks:
      - default # use its own docker network
    ports:
      - 81:81
    depends_on:
      - users
